[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4

[env]
# Enable dotenv so scripts can read PRIVATE_KEY and FUJI_RPC_URL
eth_rpc_url = "${FUJI_RPC_URL}"

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
